### ISSUE TITLE
this results is different from nucplot

### ISSUE THREAD

**Issue by zhoudreames** [ablab/VerityMap#11]
this my centromere coverage plot draw from nucplot software showing in blow,there seems to be no problem here.
![chrX](https://user-images.githubusercontent.com/54714639/147474521-2025d704-5f52-4d93-adb7-0d651d2d176c.png)
h
However，this is a obviously high peak located in the right of the centromere，Why is that? do you help me ?
![image](https://user-images.githubusercontent.com/54714639/147474825-383b817b-d823-4ae4-b6a2-bf9681b5024b.png)
In addition，How to set the font size of axis and label for resulting html files? thank you so much~ Merry Christmas to you,though this is a little late for you.

**Comment by zhoudreames** [comment]
And there are different aligned resultings for the two softeware,the veritymap contained many clipping reads,and there are not rare kmer located in such region.but winnomap2 aligned resulting is good. 
![image](https://user-images.githubusercontent.com/54714639/148870019-725b1e4c-d9a7-4a6d-b818-3e92d6de879d.png)

**Comment by seryrzu** [comment]
Hi, sorry for long response. To me that looks like a misassemble around 5Mbp. It is hard to say exactly what went wrong though... Do you expect this part of assembly to be complicated?

**Comment by zhoudreames** [comment]
the region is not complicated,  Is it caused by lack of rare kmers ？ and how to set more bigger kmer length？ thanks~

**Comment by zhoudreames** [comment]
> Hi, sorry for long response. To me that looks like a misassemble around 5Mbp. It is hard to say exactly what went wrong though... Do you expect this part of assembly to be complicated?

the region is not complicated, Is it caused by lack of rare kmers ？ and how to set more bigger kmer length？ thanks~

**Comment by seryrzu** [comment]
You can change the k-mer length in the corresponding config. For hifi the default config is in https://github.com/ablab/VerityMap/blob/master/veritymap/config/config_tm2_hifi.tsv . You can edit it and rerun make, so the config gets copied next to the binary.

Lack of rare k-mers limits VerityMap's ability to identify what's going on with the region. However, if there are no misassemblies, these regions will just have low coverage. Such excessive gaps in reads identify that this region is likely misassembled.
